### ISSUE TITLE
Lowercase commit tags

### ISSUE THREAD

**Issue by marrip** [JPeer264/node-semantic-git-commit-cli#108]
Hi,

I ran into a problem with sgc-cli. I am using this [action](https://github.com/amannn/action-semantic-pull-request) as part of my CI and they use these [types](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type) as a base. Unfortunately, the don't allow tags to start with a capital letter. Would it be possible to add an option to change that if needed? Cheers.

**Comment by JPeer264** [comment]
Hey. If I understand you correctly you can create a `.sgcrc` in your project root which includes following config:

```json
{
  "lowercaseTypes": true
}

**Comment by marrip** [comment]
Perfect! Cheers for getting back to me so fast! 🎉
