### ISSUE TITLE
New Question

### ISSUE THREAD

**Issue by JPeer264** [JPeer264/node-semantic-git-commit-cli#18]
Add `scope` to the commits:
`<type>(<scope>): <subject>` (https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format).

**Expected behavior:**
A new question (type: `input`). If there is some input, a scope will be added to the commit message. An empty input would not append any topic.

**Comment by JPeer264** [comment]
@rudolfsonjunior what you think about it?

**Comment by rudolfsonjunior** [comment]
@JPeer264 Yes i think this is a good idea.
