### ISSUE TITLE
Breaking Changes

### ISSUE THREAD

**Issue by JPeer264** [JPeer264/node-semantic-git-commit-cli#25]
- [x] Change `emojies` to the correct plural `emoji`
- [x] Set the default for `emoji` to `false`
- [x] Remove `init` from the list, and implement it as "*just at the beginning*"

**Comment by JPeer264** [comment]
@rudolfsonjunior are there any other breaking changes we can implement now? This would be a good opportunity to collect them and release them all at once.

**Comment by rudolfsonjunior** [comment]
@JPeer264 Right now, I could not think of some other changes, but I will let you know, if something comes into my mind.
