### ISSUE TITLE
Inherit mode

### ISSUE THREAD

**Issue by JPeer264** [JPeer264/node-semantic-git-commit-cli#26]
**Use case:**
If you just want just to overwrite, e.g., the `rules` you have to write the `.sgcrc` all over again. 

**Possible solution:**
In those special cases it would be good to have a `inherit` mode. So if you just want to change `"emojies: true"` to `"emojies: false"` you can write the config as follows:

```json
{
  "emojies": false,
  "inherit": true
}
```

If you just want to inherit the default `types` you can write it as follows:

```json
{
  "emojies": false,
  "inherit": "types"
}
```

or

```json
{
  "emojies": false,
  "inherit": [
    "types"
  ]
}
```

**Option definition:** 

**Type:** `boolean | array | string`
**Default**: `false`

**Comment by rudolfsonjunior** [comment]
I think this would be an awesome new feature.

**Comment by JPeer264** [comment]
(for the record, we got rid of this mode, because we will always have the default values)
