### ISSUE TITLE
Show commit message length if too long

### ISSUE THREAD

**Issue by dani-sc** [JPeer264/node-semantic-git-commit-cli#36]
Currently, if the commit message entered is too long, this message is shown:
> The commit message is not allowed to be longer as 72. Consider writing a body.

It would be nice if it would also outline how long the message is currently, e.g.

> The commit message is not allowed to be longer as 72, but is 85. Consider writing a body.

**Comment by JPeer264** [comment]
Totally agreed. This one is good.
