### ISSUE TITLE
does it work with semantic-release 8.0.0 ? 

### ISSUE THREAD

**Issue by jy95** [JPeer264/node-semantic-git-commit-cli#37]
Hello,

I have a issue https://github.com/semantic-release/semantic-release/issues/424 and I wonder if it can be related to this ?

Thanks

**Comment by JPeer264** [comment]
Hey thanks for your issue.

It should actually work, as this library basically just makes commits. I will try it in couple of hours, when I have time and give you my report.

**Comment by JPeer264** [comment]
@jy95 seems like you have to follow the angular commit styleguide, which is kinda mandatory for `semantic-release`. `semantic-git-commit-cli` follows by default a mixed styleguide. If you want to publish it now, you have to [analyze your commits](https://github.com/semantic-release/semantic-release#analyzecommits) and after that you can do following:

You can either create a global `.sgcrc` (in your homedirectory) or a local one in your project root with following settings:

```js
{
  body: true,
  scope: true,
  rules: {
    'max-char': 100
  },
  types: [
    {
      type: 'build',
      description: 'Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)'
    },
    {
      type: 'ci',
      description: 'Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)'
    },
    {
      type: 'docs',
      description: 'Documentation only changes'
    },
    {
      type: 'feat',
      description: 'A new feature'
    },
    {
      type: 'fix',
      description: 'A bug fix'
    },
    {
      type: 'perf',
      description: 'A code change that improves performance'
    },
    {
      type: 'refactor',
      description: 'A code change that neither fixes a bug nor adds a feature'
    },
    {
      type: 'style',
      description: 'Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)'
    },
    {
      type: 'test',
      description: 'Adding missing tests or correcting existing tests'
    }
  ]
}
```

Soon there will be a feature, to easily extend commit styleguides from different companies/libraries.

**Comment by jy95** [comment]
Thanks for your answer.
Ok for the .sgcrc example : I though it was by default the same that semantic-release.
So do you know any plugin for default config of semantic-git-commit-cli ?
Good luck for this new feature.

**Comment by JPeer264** [comment]
Soon there will be a plugin/preset, maybe called `sgc-preset-angular`, so then you can just write following in your `.sgcrc` (instead of the current method):

```js
{
  "extends": "angular"
}
```
Does this answer your question about the plugin?

Thanks 😃

**Comment by jy95** [comment]
almost XD I was talking about the analyzeCommits plugin ...

**Comment by JPeer264** [comment]
Ha, nope not yet. But I can make one now. Doesn't seem to be hard.

**Comment by jy95** [comment]
why not ^^ It will be a great asset for syc.

**Comment by JPeer264** [comment]
I will ping you as soon as the analyzer is ready 👍

**Comment by jy95** [comment]
No problemo, I can wait. I will be glad to help you.
You also check how they have done their default implementation : https://github.com/semantic-release/commit-analyzer/blob/master/src/index.js

**Comment by JPeer264** [comment]
@jy95 the package is now available at [sgc-commit-analyzer](https://github.com/JPeer264/sgc-commit-analyzer).

If you want to help me you can improve the docs (some usage guide like [here](https://github.com/JPeer264/node-semantic-git-commit-cli#installation)).

**Comment by jy95** [comment]
done, added basic doc . Funny fact, their changelog generator follows also AngularJS Commit Message Conventions. I think I will need to rewrite one custom for sgc

**Comment by JPeer264** [comment]
Thanks 👍 
Hm, doesn't the changelog generator uses `analyzeCommits` as well? So, am I understanding it correct, that the changelog won't get generated?

**Comment by jy95** [comment]
https://github.com/semantic-release/release-notes-generator

**Comment by JPeer264** [comment]
Those guys 🙄 
Yeah I would highly appreciate it if you can write a custom one for `sgc`.

**Comment by jy95** [comment]
I check what they used for analyze commits : for angular, it is https://github.com/conventional-changelog/conventional-changelog/tree/c146f2a67ac8127423fe24cc0cbe304cfa637fe3/packages/conventional-changelog-angular

**Comment by jy95** [comment]
Someone has created a solution to work with sgc:
https://github.com/semantic-release/semantic-release/issues/426#issuecomment-325791943

**Comment by JPeer264** [comment]
Awesome. Seems that it was easier that I thought 👍 
Thanks for your update. Can you maybe update `semantic-git-commit-cli` docs, maybe a subheading in `Usage` if someone is using `semantic-release`?

**Comment by jy95** [comment]
Enjoy, PR waiting for approval
