### ISSUE TITLE
Rename prefix to type

### ISSUE THREAD

**Issue by JPeer264** [JPeer264/node-semantic-git-commit-cli#4]
@rudolfsonjunior how about changing the name in the config `prefix` to `type`:

from: 
```js
{
  "emoji": "",
  "prefix": "Look on this line",
  "description": ""
}
```
to:

```js
{
  "emoji": "",
  "type": "Look on this line",
  "description": ""
}
```

**Comment by dani-sc** [comment]
👍 I agree, type is more appropriate.

**Comment by rudolfsonjunior** [comment]
Yes, I will add it.

**Comment by JPeer264** [comment]
@rudolfsonjunior nice, thanks - I will push an updated readme soon. Can you change it there as well? 

So the name change is going to be in one commit.

**Comment by rudolfsonjunior** [comment]
@JPeer264 I renamed it to type. Now we have a unlikely naming convention. 
```json
"types":{
  "emoji": "",
  "type": "",
  "description": ""
}
```
so it is types.type now, this could be a bit confusing?

**Comment by JPeer264** [comment]
it will never be `types.type` (`types` is an array) - it could be `type.type` if we do:

```js
types.forEach((type) => {
  console.log(type.type);
});
```

But `type` would be still a better naming convention for users.

**Comment by rudolfsonjunior** [comment]
That is true. It is type.type for now in `sgcPromt.js`.
