### ISSUE TITLE
Readme: Installation with Yarn

### ISSUE THREAD

**Issue by omar10594** [JPeer264/node-semantic-git-commit-cli#45]
Should be

`yarn global add semantic-git-commit-cli`

If you use `add` before `global`, you will get the global dependency installed on the current project (and this dependency as well).
![screen shot 2017-09-19 at 11 39 41 am](https://user-images.githubusercontent.com/9435510/30609213-9a2e9dfc-9d2f-11e7-9faf-39a640fd885f.png)

**Comment by JPeer264** [comment]
Thanks for your issue. 

Yes you are right, thanks. A PR is highly appreciated.
