### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by JPeer264** [JPeer264/node-semantic-git-commit-cli#5]
@dani-sc @rudolfsonjunior 

we need more tests, especially for `lib/sgcPrompt.js`. Anybody experience in testing `inquirer` prompts?

**Comment by dani-sc** [comment]
What I've found so far:
[Blog: Unit Testing CLI Programs](https://glebbahmutov.com/blog/unit-testing-cli-programs/), however the npm package used ([bdd-stdin](https://www.npmjs.com/package/bdd-stdin)) is (a) [buggy](https://github.com/bahmutov/bdd-stdin/issues/2) and (b) would require quite a bit of refactoring in our code.
Something like _rewire_/_sinon_/... is also not of use, as we can't rewire process.stdin to simulate input afaik.
Last but not least, there is an [open issue concerning improved unit testing capabilities](https://github.com/SBoudrias/Inquirer.js/issues/379), but nobody is working on that yet.

**Comment by rudolfsonjunior** [comment]
#9
