### ISSUE TITLE
Option for alternative config path

### ISSUE THREAD

**Issue by Joaquin6** [JPeer264/node-semantic-git-commit-cli#60]
Right now, the only locations to provide configuration is  at `path.join(cwd, '.sgcrc')`, `path.join(homedir, '.sgcrc')` _(user's machine home directory)_, or  inside `package.json` in a `sgc` property. 
According to the [`getConfig` method](https://github.com/JPeer264/node-semantic-git-commit-cli/blob/c8361b51c08a3acb7bd37933904e50cfd8561e76/lib/getConfig.js#L9), we should be able to pass in a alternative path. However it doesn't seem to be used at all when called from the [cli module](https://github.com/JPeer264/node-semantic-git-commit-cli/blob/c8361b51c08a3acb7bd37933904e50cfd8561e76/lib/cli.js#L20).

It be nice to be able to be able to pass in the alternative path so the end user can choose where to place their config file.

**Comment by aichbauer** [comment]
I think that is a good idea. What do you think @JPeer264

**Comment by JPeer264** [comment]
Do you have a specific use case for this where you see an advantage of this feature, or a way how this could look like?

The only two ways of what I can think of is either:

1. Applying the path at each call of `sgc` e.g.: `sgc --config-path=/path/`(which, imho, might be annoying over some time)
2. Setting a (global or project wide) `sgc`s default, kinda like git (which does not exist atm) e.g.: `sgc set config-path "/path/"` or `sgc set --global config-path "/path/"`

But yeah, you are right. This parameter is not yet used. If there is a reasonable use case and a clean implementation I would consider to implement this feature.

**Comment by JPeer264** [comment]
@Joaquin6 ping

**Comment by JPeer264** [comment]
Closed due to no response. If somebody needs this feature just comment and I'll reopen this issue.
