### ISSUE TITLE
availableRules[ruleName] is not a function

### ISSUE THREAD

**Issue by MartinMuzatko** [JPeer264/node-semantic-git-commit-cli#61]
I get this error when putting rules into my `.sgcrc` and then try a commit:

![image](https://user-images.githubusercontent.com/2950505/44990206-9da83c80-af90-11e8-817a-f2fa66e70ad3.png)

``` json
{
    "scope": true,
    "lowercaseTypes": true,
    "rules": {
        "max-char": -1
    }
}
```

**Comment by JPeer264** [comment]
Hey, thanks for using sgc. Have you triedto write `maxChar` instead of `max-char`? Since v`3.0.0` we changed that.

**Comment by MartinMuzatko** [comment]
I just debugged the script, yes I need to use `maxChar`. This worked :)
Please change that in the docs.
Thanks!

**Comment by MartinMuzatko** [comment]
Anyways: there should be a proper error handling for this, this is a pretty bad hint at what is wrong :)

I'd propose something like: "The rule defined does not exist, look at the documentation to check valid rules"

**Comment by JPeer264** [comment]
that's actually an awesome idea. I hope @aichbauer or me have time soon to implement this.
