### ISSUE TITLE
Find closest .sgcrc

### ISSUE THREAD

**Issue by JPeer264** [JPeer264/node-semantic-git-commit-cli#64]
Bubble up until `.sgcrc` is found. If there is none, use the other defaults.

Possible lib: [findup-snyc](https://www.npmjs.com/package/findup-sync)

**Comment by robnester-rh** [comment]
This would be a feature we'd love to see. It would, I assume, allow us to package up our sgrc file in the git repo to ensure that commit messages generated with sgc are consistent among contributors.

**Comment by JPeer264** [comment]
Sure I'm gonna implement the feature soon :)

**Comment by JPeer264** [comment]
@robnester-rh released in v`3.5.0`
