### ISSUE TITLE
Commit improvements

### ISSUE THREAD

**Issue by JPeer264** [JPeer264/node-semantic-git-commit-cli#7]
- [x] Shorten commit descriptions
- [x] `validate` limit commit message (maybe 50/72 chars)

**Comment by dani-sc** [comment]
We could also add a warning if the commit message ends with a "."

**Comment by JPeer264** [comment]
I guess by default it shouldn't display a warning, but we can add a boolean in the config to enable this warning. `"end-with-dot": false` or similar

**Comment by dani-sc** [comment]
Yeah; that would probably also be a good idea with the commit message limit.

**Comment by JPeer264** [comment]
True!

Maybe we can add `"rules"` in the config as `"types"`. I would say we should first publish `v1.0.0, shorten the commit descriptions and then add the features with the rules.
