### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by anoblet** [JPeer264/node-semantic-git-commit-cli#70]
Is there any way to pass scope and message as arguments?

**Comment by JPeer264** [comment]
Do you mean something like this:

```sh
$ sgc -m my message -s someScope
```

This is currently not implemented. What exactly do you except if you enter this? Should this still trigger `sgc` or just commit with the correct formatting?

**Comment by anoblet** [comment]
In my ideal situation, yes that would be the syntax (sgc -s someScope -m myMessage) sgc would handle the formatting of the commit. Just a quick way to skip the UI. Love your work!

**Comment by anoblet** [comment]
That sounds awesome! I mixed up scope and type before, I use type and message right now for my commits. Setting required arguments, and only prompting for missing arguments sounds like the perfect solution.

**Comment by JPeer264** [comment]
@anoblet this will take some time as I have to implement another feature where I refactored a bit (cc: #69)

**Comment by JPeer264** [comment]
@anoblet released in v`3.2.0`. Thanks for your patience.

**Comment by anoblet** [comment]
Thanks!
