### ISSUE TITLE
Non-responsive

### ISSUE THREAD

**Issue by anoblet** [JPeer264/node-semantic-git-commit-cli#71]
Powershell becomes non-responsive after running sgc, specifying a type and a commit message. The commit goes through fine though the window hangs and needs to be closed out forcefully.

Windows 10/x64 Moved from Node 8 to Node 10 recently

**Comment by JPeer264** [comment]
Hey thanks for your issue. Did it work properly on Node v8? So you experience this issue right after you confirmed the last step?

**Comment by anoblet** [comment]
Correct

**Comment by JPeer264** [comment]
@anoblet please try `semantic-git-commit-cli@3.1.1` and reopen this issue if necessary.
