### ISSUE TITLE
Access Denied after updating to 3.2.0

### ISSUE THREAD

**Issue by ace3** [JPeer264/node-semantic-git-commit-cli#75]
Today i tried updating the sgc to version 3.2.0 
after updating, i have a access denied issues.

`─$ sgc -v
zsh: permission denied: sgc`

after downgrading to version 3.1.1, it's working again.

my stack is
-mac
-zsh
-node v10.15.1
-npm v6.9.0

anyone experince same issue ?

**Comment by JPeer264** [comment]
Hey thanks for your issue. Actually I have the same, but I thought I have troubles with my npm and wanted to repair it in the weekend. I'm gonna investigate on this.

Sorry for this issue.

**Comment by JPeer264** [comment]
@ace3 I resolved the issue and is published at v`3.2.1`. Thanks for your issue and sorry for the bug ;)
