### ISSUE TITLE
Adding body starts out with undefined and loses title line

### ISSUE THREAD

**Issue by agentofuser** [JPeer264/node-semantic-git-commit-cli#77]
# To reproduce:

- choose the commit type
- type short commit message
- choose `y` for whether to add a body to the commit message

## Expected:

My editor comes up with the first line filled out with what I'd already typed, and lets me type in the body I want.

## Actual behavior:

Editor comes up with `undefined` as the content. I thought the title line was added behind the scenes, but after typing the body and saving, only the body was present in the commit message, not the type or title message.

## Version:

v3.2.1

**Comment by JPeer264** [comment]
Hi @agentofuser 
Thanks for the issue. I was able to reproduce the bug - I am fixing this asap.

**Comment by JPeer264** [comment]
Fixed in v`3.2.2`
