### ISSUE TITLE
Optional Space between type and scope

### ISSUE THREAD

**Issue by JPeer264** [JPeer264/node-semantic-git-commit-cli#79]
`<type>(<scope>)` and `<type> (<scope>)` should be possible

**Comment by robnester-rh** [comment]
Do you have any time frame for this, I'd love to see this feature!

**Comment by JPeer264** [comment]
Hey, I'll do it now if you want to have this feature :)

**Comment by JPeer264** [comment]
https://github.com/JPeer264/node-semantic-git-commit-cli#addScopeSpace

Released in v`3.4.0`

**Comment by robnester-rh** [comment]
Thank you so much, super useful for my team!
