### ISSUE TITLE
Enable option to add footer at the end of the commit message

### ISSUE THREAD

**Issue by ssuperczynski** [JPeer264/node-semantic-git-commit-cli#82]
CI tools like Gitlab, Github, Bitbucket or Jira reads footer of the commit.
It is helpful to link, or to trigger an action if footer of the commit is applied.

It is described in the https://www.conventionalcommits.org/en/v1.0.0/#summary

I'd like to add this feature. Let me know if this sounds good to you to be added.

```
<type>(<scope>)<delimiter> <message>

<body>

<footer>
```

**Comment by JPeer264** [comment]
Sounds great. But what if there is no `<body>` applied? Are there 2 or 3 breaks?

(`\n`'s are just for clarification)
```
<type>(<scope>)<delimiter> <message>
\n
\n
<footer>
```
or
```
<type>(<scope>)<delimiter> <message>
\n
\n
\n
<footer>
```

Or is a body mandatory for a footer?

**Comment by JPeer264** [comment]
ping @ssuperczynski

**Comment by aaron-junot** [comment]
@JPeer264 I would like to upvote this issue (I came here to open a similar request and found it already exists).

I would suggest that it's either that the body is mandatory for the footer, or that it's 2 blank lines as in your first example.

AngularJS has some additional information from this [Google Doc](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit).
