### ISSUE TITLE
Use rawlist for "type" prompt

### ISSUE THREAD

**Issue by jwhitmarsh** [JPeer264/node-semantic-git-commit-cli#83]
This would enable a keyboard shortcut to jump to a type (screenshot below). What are the maintainers' thoughts on this? Maybe it could be behind a config option? Happy to put in a PR if this idea has merit. 

![image](https://user-images.githubusercontent.com/8026009/69330282-8bc0c100-0c4a-11ea-9f80-2660b0be6516.png)

Edit: I want to add - thanks for this great tool, I was thinking of creating something like the [rebase-editor](https://www.npmjs.com/package/rebase-editor) but for commits, but you beat me to it!

**Comment by JPeer264** [comment]
Numbers are a great idea actually - is it still possible to move around with the arrow keys and press enter on the highlighted one? (like the behavior right now)

Btw your tool looks pretty neat :)

**Comment by jwhitmarsh** [comment]
You can move around using the arrow keys, but not j & f (which is supported by the standard `list` prompt). 

This is the change that is required, if you just want to test it out locally:

![image](https://user-images.githubusercontent.com/8026009/69412908-b4f35700-0d07-11ea-8ec6-0771973d3fcd.png)

Rebased-editor is great! Not mine thought, just my inspiration for looking for a commit version and leading me to this!

**Comment by JPeer264** [comment]
I am not sure about this, as it will be just in this list. All other lists will have a different (the current) behavior, this could be kinda misleading and confusing. Maybe the autocomplete plugin makes more sense here? https://github.com/mokkabonna/inquirer-autocomplete-prompt

With that the current behavior stays the same, and the terms are also searchable. Here the terms could also be prefixed with fixed numbers to be searchable. What you think about that?

**Comment by jwhitmarsh** [comment]
Ah cool, the autocomplete prompt looks great! I agree that that makes more sense, it also means that people don't have to remember that "1 is fix, 2 is feat" etc.

**Comment by JPeer264** [comment]
I am gladly accepting PRs. I am kinda busy RN and just could implement it by end of this week :)

**Comment by JPeer264** [comment]
Added in v`3.6.0`
